name: DooN_Build_Final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Tweak
        uses: hacker-9/action-theos-make@main
        with:
          archs: 'arm64 arm64e'
          sdk: 'https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz'

      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: DooN-Dylib
          path: 'packages/*.deb' # أو جرب تخليه .theos/obj/debug/*.dylib