name: DooN_Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Theos
        run: |
          sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
          sudo chown -R $(id -u):$(id -g) /opt/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* /opt/theos/sdks-master/
          # كود لضمان وجود الـ SDK
          git clone https://github.com/theos/sdks.git /opt/theos/sdks
          
      - name: Build Dylib
        run: |
          export THEOS=/opt/theos
          make package FINAL_PACKAGE=1
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: DooN-Dylib
          path: .theos/obj/debug/*.dylib